### PR TITLE
Suppressing kernel messages to avoid cluttering prompts

### LINKED ISSUE #17: Suppress linux kernel messages after login
They clutter up the display and obscure the first prompt in the script.

### PR DESCRIPTION
**Pull request by umbernhard**
Closes #17.

### CODE REVIEW

**Comment by umbernhard** [comment]
@carolinemodic the only issue with this is that there's a long time where the screen just says "Booting archlinux". Should I try to find a way to put up a splash screen with a loading bar?

**Comment by carolinemodic** [comment]
@umbernhard what do you mean by "a long time" like 10 seconds, or 10 minutes?

**Comment by umbernhard** [comment]
It's like ~30 seconds

**Comment by umbernhard** [comment]
(I'm working on getting you a screencapture so you can see)

**Review by carolinemodic — APPROVED** [review]

**Pull request merged**
